### ISSUE TITLE
[Bug] Vanilla lantern is very slow to break down

### ISSUE THREAD

**Issue by lays24mc** [SuperMartijn642/AdditionalLanterns#1]
**Version Info**
- Minecraft 1.17.1
- Additional Lantern, 1.0.0a-mc1.17
- SuperMartijn642's Core lib, 1.0.12-mc1.17
- Forge, 37.0.85

**Description of the Bug**

The vanilla lantern, which is "replaced" by the mod, takes as long to break as an obsidian. I have tested the other lanterns, and they break normally.

**Steps to Reproduce**
Place a normal lantern and have a try to break this with a diamond pickaxe :D

**Comment by SuperMartijn642** [comment]
I fixed it now in Additional Lanterns 1.0.0b for Minecraft 1.17.

Thank you for reporting the issue!
