### ISSUE TITLE
Current 1.16.5 Version of Additional Lanterns crashes

### ISSUE THREAD

**Issue by ModernGamingWorld** [SuperMartijn642/AdditionalLanterns#10]
After you updated your SuperMartijn Core Lib, Now additional Lanterns are crashing cause it requires 1.0.9 or above, and below 1.1.0

**Comment by ModernGamingWorld** [comment]
[crash-2023-01-02_15.36.35-fml.txt](https://github.com/SuperMartijn642/AdditionalLanterns/files/10333534/crash-2023-01-02_15.36.35-fml.txt)

**Comment by SuperMartijn642** [comment]
Please update Additional Lanterns to 1.0.2.

**Comment by ModernGamingWorld** [comment]
@SuperMartijn642 you did not release version 1.0.2 on Curseforge for 1.16.5, There are only versions for 1.14, 1.17, 1.18, and 1.19

**Comment by SuperMartijn642** [comment]
CurseForge servers somehow messed up half the uploaded files for Additional Lanterns, so I had to reupload them today. If you still can't see them, you can download the update on Modrinth here: https://modrinth.com/mod/additional-lanterns/versions
