### ISSUE TITLE
[Bug] Unable to craft lantern

### ISSUE THREAD

**Issue by SorcererAssassin** [SuperMartijn642/AdditionalLanterns#14]
I'm unable to craft the normal lantern in 1.12.2, after I updated the mod. 
![2023-02-26_18 51 13](https://user-images.githubusercontent.com/60132536/221427397-bfcd29c7-12c6-48b8-a192-de7810517a38.png)

**Comment by SuperMartijn642** [comment]
Please use the appropriate template. What version of Additional Lanterns are you using?

**Comment by SorcererAssassin** [comment]
I wasn't aware of a template, my apologies. I'm using version 1.0.4

**Comment by SuperMartijn642** [comment]
Seems I forgot to add the regular lantern recipe in 1.12 after converting everything to data generators 🤦‍♂️
It is fixed now in version 1.0.4a for Minecraft 1.12.

Thank you for reporting the issue!
