### ISSUE TITLE
[Question] What version do I need for this mod which is imported SuperMartijn642's Core Lib?

### ISSUE THREAD

**Issue by JohnDeereLiebhaber** [SuperMartijn642/AdditionalLanterns#15]
**Question**
What version do I need for this mod which is imported SuperMartijn642's Core Lib?

Game version: 1.12.2

Thanks in advance

**Comment by SuperMartijn642** [comment]
Just use the latest version for 1.12.2.
![image](https://user-images.githubusercontent.com/12382965/222527041-feec780a-5d5a-43e2-b256-8d2e074da3fa.png)

**Comment by JohnDeereLiebhaber** [comment]
Thanks very much!

now I have these errors see attachment.

Kind regards

![Screenshot 2023-03-03 153624](https://user-images.githubusercontent.com/82206068/222748846-40d6a96d-2050-4309-b583-49feeba9bcad.png)

![Screenshot 2023-03-03 153547](https://user-images.githubusercontent.com/82206068/222748889-d63fc7fa-f01a-4771-9500-11dfdb74a024.png)

![Screenshot 2023-03-03 153506](https://user-images.githubusercontent.com/82206068/222748942-21db172c-23ea-4647-afff-cfe8cda0c779.png)

**Comment by SuperMartijn642** [comment]
This seems to be unrelated to Additional Lanterns. Please figure out what mods are producing that issue and report it to them.
