### ISSUE TITLE
[Crash] Placing lantern on abnormal block crashes game

### ISSUE THREAD

**Issue by ianm1647** [SuperMartijn642/AdditionalLanterns#17]
**Version Info**
- Minecraft 1.19.4
- Fabric Loader 0.14.19
- Fabric API 0.79.0
- Additional Lantern 1.0.4
- SuperMartijn642's Core lib 1.1.7

**Steps to Reproduce**
Place vanilla lantern on leaves, half slabs, sometimes fences, etc.

**Crash report (~/logs/latest.log)**
[Crash report](https://pastebin.com/YCUuvLqz)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.0.4a for Fabric on 1.18 and 1.19.

Thank you for reporting the issue!
