### ISSUE TITLE
[Bug] Normal lanterns don't turn off when powering the bloct that is on

### ISSUE THREAD

**Issue by TheAlchemist404** [SuperMartijn642/AdditionalLanterns#20]
**Version Info**
- Minecraft 1.19.2 [Forge]
- Additional Lantern 1.04
- SuperMartijn642's Core lib 1.1.9a

**Description of the Bug**
The behavior of the regular lantern is inconsistent with the other lanterns when powered by redstone, it updates the texture of the block but doesn't turn off the lantern unless it gets turn off twice

**Steps to Reproduce**
Place a normal lantern [additionallanterns:normal_lanterns] on any opaque block that can be hard powered by redstone, then power the block, unpower it and power it again  

**Screenshots**
_When initially placed_
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/37026488/bde42eba-4d97-44e1-9791-52857effdfc4)

_When powered for the first time_
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/37026488/c43e30eb-eee6-4c42-8a72-bfee8329eef5)

_Unpowered again_
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/37026488/f542358f-c465-4c0e-81bf-b69cda3b3d3e)

_Powered for the second time_
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/37026488/670ef12e-2a7d-4dc3-900b-8370016d4a06)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.0.5 of Additional Lanterns.
Thank you for reporting the issue!
