### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Abhainn-Leth** [SuperMartijn642/AdditionalLanterns#24]
**Version Info**
- Minecraft version 1.20.1 (fabric loader installer version 0.11.2)
- 1.0.4a - fabric
- SuperMartijn642's Core lib 1.1.9 fabric

Description of the Bug:
Vanilla lantern item texture is broken both in inventory and in hand. In a multiplayer server setting, this is also the case but disallows the vanilla lantern to be placed. Only the mod version of the vanilla lantern can be placed. However, when middle clicking the modded version of the vanilla lantern, the player gets the regular vanilla lantern with broken textures. (Server is using the same versions listed above.)

Screenshots:
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/92332705/27c46a82-d64c-45db-be51-9e6a7b3e9a5b)
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/92332705/071bad30-fc48-434e-82ec-9ad7c1a3e46c)

**Comment by SuperMartijn642** [comment]
I fixed the middle click giving the wrong item in version 1.1.10a of my core library now.

As for the broken model, it seems to work fine with just Additional Lanterns installed:
![image](https://github.com/SuperMartijn642/AdditionalLanterns/assets/12382965/24f07b22-05e1-478e-a788-554dd1a4edeb)

Are you using other mods and if so, could you narrow down which other mods are needed to reproduce the issue?

**Comment by Abhainn-Leth** [comment]
I tested the mod in isolation with only your core mod, Fabric API and Cloth Config before creating the bug report as I wanted to ensure it wasn't a conflict. However, this was with version 1.1.9-1.20 (file name: supermartijn642corelib-1.1.9-fabric-mc1.20) of your core mod which is very likely the issue. 

I'll be sure to download the latest core mod as well as check the mod featured is up to date and that'll likely fix things. In which case, sorry about the false report, I'm using this mod as part of a private server pack, as implied by issues found in a multiplayer setting and it seems to have slipped through the cracks when I was doing the update check. Of course, if there's still an issue or one found in future then I'll be sure to open another ticket.

Thanks for your help!

**Comment by SuperMartijn642** [comment]
> seems to have slipped through the cracks when I was doing the update check

No you're all good, I updated my core library because of your issue report 🙂
I definitely appreciate the report!
