### ISSUE TITLE
[Feature] Deepslate and Copper/Gold sets

### ISSUE THREAD

**Issue by Ultimushadow** [SuperMartijn642/AdditionalLanterns#25]
While the basalt set comes close ish in color, it's just not the right gray, there isn't a set that's a little darker to fit into deepslate builds. Also, copper does not have a good 1 to 1 color, and I feel like colored lights do best in more industrial settings which copper lanterns would be perfect for. At present, you can maybe get away with red sandstone for pure, granite for exposed, and prismarine for oxidized, but there is no weathered match. Gold has a similar issue, no match, would look great along with the quartz set.

Preferably, a deepslate set, a gold set, and a copper set that can age/be waxed/be scraped like other copper blocks

Thanks for the work on this mod!

**Comment by SuperMartijn642** [comment]
I added a bunch of new blocks now in version 1.1.0 including deepslate, gold, and copper. The copper lanterns and chains will also oxidize and can also be waxed.
Thank you for the suggestion!

**Comment by Ultimushadow** [comment]
Awesome, thank you!!
