### ISSUE TITLE
[Question] Necessity of SuperMartijn642's Core Lib

### ISSUE THREAD

**Issue by SquigMo** [SuperMartijn642/AdditionalLanterns#26]
**Question**
Additional Lanterns shows that it's been updated for forge 1.20.1, but it also shows a required dependency on 
SuperMartijn642's Core Lib, which has been updated for fabric 1.20.1 but not forge 1.20.1. 

At this time is Additional Lanterns actually compatible with forge 1.20.1 or will I have to wait for 
SuperMartijn642's Core Lib to be updated for forge 1.20.1 as well?

Thanks!

**Comment by SuperMartijn642** [comment]
My core library is already available for Forge on 1.20.1 https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib/files/4601830.
You can use the filters on the 'files' tab to filter by mod loader and Minecraft version.
