### ISSUE TITLE
[Bug] [1.12.2] Stone brick chains have empty recipe

### ISSUE THREAD

**Issue by brisingraerowing** [SuperMartijn642/AdditionalLanterns#29]
**Version Info**
- Minecraft, 1.12.2
- Additional Lantern, 1.1.0-1.12.2
- SuperMartijn642's Core lib, 1.1.12

**Description of the Bug**
Stone brick chains have an empty recipe, resulting in them appearing in the crafting output when nothing is inputted, and can be extracted infinitely.

**Steps to Reproduce**
Install AL and JEI.
View the Stone Brick Chain recipe

**Screenshots**
![2023-08-01_19 53 03](https://github.com/SuperMartijn642/AdditionalLanterns/assets/250409/c176b899-15bf-43e7-ab00-61ef3a06354f)

**Comment by SuperMartijn642** [comment]
`new ItemStack(Blocks.STONEBRICK, 0)`
Whoops, I guess that means amount=0, not metadata=0 🤦‍♂️
Gotta love 1.12

I fixed it now in version 1.1.1a for Minecraft 1.12. Thank you for reporting the issue!
