### ISSUE TITLE
[Feature] Add Support With Shimmer

### ISSUE THREAD

**Issue by HavocStudio2** [SuperMartijn642/AdditionalLanterns#30]
I would like to see support added with Shimmer
https://github.com/Low-Drag-MC/Shimmer

**Comment by SuperMartijn642** [comment]
I tried adding support with Shimmer, however the mod wouldn't even start on Forge 1.20 or 1.20.4. On Forge 1.20.1, the mod does launch without crashing, but the code examples they provide here just don't seem to do anything in game: https://github.com/Low-Drag-MC/Shimmer/wiki/Coloured-Lights.

Maybe I'll come back to it if Shimmer fixes these issues, but for now I don't think there's much I can do.
