### ISSUE TITLE
[Crash] when opening creative item menu with version 1.1.1

### ISSUE THREAD

**Issue by kennyrkun** [SuperMartijn642/AdditionalLanterns#31]
**Version Info**
- Minecraft 1.20.1
- Additional Lantern, 1.1.1
- SuperMartijn642's Core lib, 1.1.12a
- Forge

**Steps to Reproduce**
Open the creative menu in any gameworld. It's possible there's a conflict with other mods, but I don't know enough about crash reports to figure out which one. List of other mods is included with the crash report.

**Crash report**
...
[crash-2023-08-09_11.33.22-client.txt](https://github.com/SuperMartijn642/AdditionalLanterns/files/12325709/crash-2023-08-09_11.33.22-client.txt)

**Comment by SuperMartijn642** [comment]
Seems to work fine with just Additional Lanterns installed. Please narrow down which other mod is needed to reproduce the issue.
