### ISSUE TITLE
[Crash] Mixin Error with Sodium + MovingElevators

### ISSUE THREAD

**Issue by Zykana** [SuperMartijn642/AdditionalLanterns#32]
**Version Info**
- Minecraft, 1.20.1
- Fabric, 0.14.22
- Iris, 1.6.7
- Sodium, 0.51
- Indium, 1.0.21
- Moving Elevators, 1.4.3a
- SM642CoreL, 1.1.12b
- SM642ConL, 1.1.7

**Steps to Reproduce**
Try to run modpack with said above noted mods

**Crash report (~/logs/latest.log)**
(https://paste.atlauncher.com/view/4f6b26f9-325a-4b3c-ad25-66137572ee78)

**Comment by SuperMartijn642** [comment]
What does this have to do with Additional Lanterns 🤔

**Comment by Zykana** [comment]
Whoops I posted to the wrong spot, sorry.
