### ISSUE TITLE
[Bug] 1.12.2 - All chains have the name 'Stone Bricks Chain'

### ISSUE THREAD

**Issue by brisingraerowing** [SuperMartijn642/AdditionalLanterns#33]
**Version Info**
- Minecraft, 1.12.2
- Additional Lantern, 1.1.1a
- SuperMartijn642's Core lib, 1.1.12b

**Description of the Bug**
All chains are named 'Stone Bricks Chain'

**Steps to Reproduce**
Look at the chains in JEI

**Screenshots**
![2023-08-27_20 43 17](https://github.com/SuperMartijn642/AdditionalLanterns/assets/250409/77513d62-bb23-4f7f-9d7d-5881c88c115f)
![2023-08-27_20 43 19](https://github.com/SuperMartijn642/AdditionalLanterns/assets/250409/fd9e450e-1754-4eeb-bc78-f9e7dee356ea)
![2023-08-27_20 43 21](https://github.com/SuperMartijn642/AdditionalLanterns/assets/250409/02863a44-ba01-4685-a646-706dbd88c8ff)
![2023-08-27_20 43 23](https://github.com/SuperMartijn642/AdditionalLanterns/assets/250409/4a3d5e8e-062a-4140-972d-17db4123cf09)
![2023-08-27_20 43 25](https://github.com/SuperMartijn642/AdditionalLanterns/assets/250409/2e2b1729-fe96-4029-bd3c-d2d76da14dde)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.1b for Minecraft 1.12.
Thank you for reporting the issue!
