### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by n-jones0** [SuperMartijn642/AdditionalLanterns#34]
**Version Info**
- Minecraft, 1.20.1
- Additional Lantern, 1.1.1
- SuperMartijn642's Core lib, 1.1.8
- Quilt Loader 0.20.2

**Steps to Reproduce**
Additional Lanterns throws an error not detecting the library, even though Durability Tooltip 1.1.5 is installed and working

**
-- Error 1 --

Additional Lanterns requires version [1.1.0, 1.2.0) of supermartijn642corelib, which is missing!

- <mods>/additionallanterns-1.1.1-fabric-mc1.20.jar

**

**Comment by SuperMartijn642** [comment]
You probably have my config library and not the core library. Additional Lanterns requires them both.
