### ISSUE TITLE
[Crash] forge 1.20.4 crash

### ISSUE THREAD

**Issue by nickademas** [SuperMartijn642/AdditionalLanterns#37]
**Version Info**
- Minecraft 1.20.4
- Additional Lanterns 1.1.1
- SuperMartijn642's Core lib 1.1.16a

**Steps to Reproduce**
launch the game

**Crash report (~/logs/latest.log)**
...
[latest.log]
[latest.log](https://github.com/SuperMartijn642/AdditionalLanterns/files/14213607/latest.log)

**Comment by SuperMartijn642** [comment]
Are you sure this is the correct log? There appears to be no crash in the log.

**Comment by nickademas** [comment]
Yeah, my bad. Now it's the correct one

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.1.1a for Fabric and Forge on Minecraft 1.20.4.
Thank you for reporting the issue!
