### ISSUE TITLE
[Suggestion] Change the Recipe for chains to include iron inguts

### ISSUE THREAD

**Issue by HojoTimberwolf** [SuperMartijn642/AdditionalLanterns#39]
I noticed that most of the recipes for making the chains are 3 similar blocks in a vertical line. This is similar to the vertical slabs recipe for [Enchanted Vertical Slabs mod](https://github.com/Enchanted-Games/vertical-slabs) created by enchanted-games. Would it be more appropriate to have 2 iron ingots around the block of choice or have 2 blocks around 1 iron ingot?

**Comment by SuperMartijn642** [comment]
Recipe conflicts are bound to happen. There is no way to avoid all recipe conflicts. Instead, use a mod like [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph) which allows you to pick which recipe you want.

> Would it be more appropriate to have 2 iron ingots around the block of choice or have 2 blocks around 1 iron ingot?

I don't really like having to use iron to craft chains for arbitrary blocks.
