### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gabgat** [SuperMartijn642/AdditionalLanterns#4]
A friend of mine has translated the mod to italian, i'll send you the file in .txt because github does not support .json in this field...
Can you update the mod? We need Italian for a modpack. Thank you!
[it_it.txt](https://github.com/SuperMartijn642/AdditionalLanterns/files/8569661/it_it.txt)

**Comment by SuperMartijn642** [comment]
Thank you for the translations!

Could you submit them as a pull request? That way git will show that you were the one who contributed the translations and it allows me to easily merge them.

To submit a pull request:
Press 'Create new file' in the lang folder here https://github.com/SuperMartijn642/AdditionalLanterns/tree/1.18/src/main/resources/assets/additionallanterns/lang
![image](https://user-images.githubusercontent.com/12382965/166103921-298da75c-2b41-4e50-82e1-03991706851f.png)
Then enter `it_it.lang` as the file name and put your translations as the file contents. Once you have entered the translations, simply press 'Commit new file' and submit the pull request 🙂
![image](https://user-images.githubusercontent.com/12382965/166104093-def3234f-28ca-474a-959b-69ed6edd2ec2.png)

**Comment by SuperMartijn642** [comment]
Closing this due to no response.
