### ISSUE TITLE
[Bug] ... Why is my character doing a nazi salute with this mod

### ISSUE THREAD

**Issue by crystallineSage** [SuperMartijn642/AdditionalLanterns#43]
![lanternsalute](https://github.com/SuperMartijn642/AdditionalLanterns/assets/161542158/70957ebf-7555-4ca5-9fd2-4de1f9486166)
**Version Info**
- Minecraft, ...
- Additional Lantern, ...
- SuperMartijn642's Core lib, ...

**Description of the Bug**
...
yea this is horrible

**Steps to Reproduce**
...
i have a few mods but i've only been able to pinpoint this mod as making me do it rather than any compatibilities. 1.20.1 forge

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Please properly fill in the template. What version of Additional Lanterns are you using?

Additional Lanterns does not do anything related to the player, it just adds lanterns. Please narrow down which other mod is needed to reproduce the issue.
