### ISSUE TITLE
[Feature] ... Add Chains to the c:chains tag for NeoForge 1.21.1

### ISSUE THREAD

**Issue by ModernGamingWorld** [SuperMartijn642/AdditionalLanterns#47]
**Is your feature request related to a problem? Please describe.**

... HI, I would like to see if you could add your chains to the c:chains tag so that I and other modpack creators dont have to do it ourselves

**Describe the solution you'd like**

... having the chains added to the proper tag to help with Mod compat and modpack developers modpacks

**Comment by SuperMartijn642** [comment]
This seems to be the same as #41. Last time I looked at this, the `c:chains` tag didn't exist yet in Forge and NeoForge, but it seems it has since been added to NeoForge.
Not sure when I will have time to update Additional Lanterns.

Closing this in favor of #41.
