### ISSUE TITLE
[Bug] [1.12.2] Item Names Won't Display Correctly

### ISSUE THREAD

**Issue by FunElectric** [SuperMartijn642/AdditionalLanterns#5]
**Version Info - 1.12.2 - Mods List**
> **[Default]:** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge.
> **[Added]:** Additional Lantern, SuperMartijn642's Core Lib.

**Description of The Bug**
> In 1.12.2, the Lanterns', Chains', and mod's names do not work properly in the Creative Mode Inventory and in the toolbox.
> **[Exception]:** Oddly enough, F3 displays their names correctly.

**Steps to Reproduce**
> Install the mod inside a 1.12.2 CurseForge Modpack, enter a world of choice, and simply browse through the Creative Mode Inventory.

**Screenshots**

![2022-06-06_00 52 42](https://user-images.githubusercontent.com/87086653/172072516-9ba447a6-749c-4298-a011-313c24494896.png)

![2022-06-06_00 52 51](https://user-images.githubusercontent.com/87086653/172072523-9ab1d271-4a08-4d0d-810c-50ae7f0b2506.png)

![2022-06-06_01 14 22](https://user-images.githubusercontent.com/87086653/172072791-8f22ac5b-366a-4226-b437-70606e87226e.png)

![2022-06-06_00 53 04](https://user-images.githubusercontent.com/87086653/172072527-4d4205b8-1fa5-4797-80df-fe713ab8f352.png)

![2022-06-06_00 53 10](https://user-images.githubusercontent.com/87086653/172072530-13e89e28-62c3-4e90-bd3f-0c04fa84ad05.png)

**Comment by SuperMartijn642** [comment]
What version of Additional Lanterns are you using?

**Comment by FunElectric** [comment]
I'm using version 1.0.1 [additionallanterns-1.0.1-mc1.12.jar] [Uploaded: 4/20/2022]. It's the latest version available for 1.12.2.
> I forgot to mention that I already tried this mod on two separate modpacks, with the same results, so there doesn't seem to be any mods causing conflict, nor would reinstalling it change the outcome.

**Comment by FunElectric** [comment]
**[Update]:**
> I downgraded to version 1.0.0 [additionallanterns-1.0.0-mc1.12.jar] [Uploaded: 7/11/2021]. The mod works as intended in this version. Odd...

![2022-06-06_03 17 22](https://user-images.githubusercontent.com/87086653/172076526-38a4f7be-923c-4425-b750-8f47eb7e305b.png)

**Comment by SuperMartijn642** [comment]
Seems I simply forget to rename the translations file from 'en_US.lang' to 'en_us.lang' when I updated the `pack.mcmeta`'s pack_format.
Luckily it only affects 1.12. Still weird noone reported it until now.

Anyways, it is fixed now in Additional Lanterns 1.0.1a for Minecraft 1.12.
Thank you for reporting the issue!
