### ISSUE TITLE
[Bug] First Person View is weird

### ISSUE THREAD

**Issue by RedBeast1959** [SuperMartijn642/AdditionalLanterns#7]
**Version Info**
- Minecraft: 1.19.2
- Additional Lantern: additionallanterns-1.0.1a-forge-mc1.19.jar
- SuperMartijn642's Core lib: supermartijn642corelib-1.0.19a-forge-mc1.19.jar

**Description of the Bug**
...
In first person view, additional lantern held on hand is too low. Too low for seeing its texture.

**Steps to Reproduce**
...

**Screenshots**
...
![2022-09-04_22 22 28](https://user-images.githubusercontent.com/100399264/188316126-43bf37ff-2cf0-4f3d-9f5a-889e7c59e6dd.png)

Normal soul lantern(which is not included in the mod) in first person view

![2022-09-04_22 22 39](https://user-images.githubusercontent.com/100399264/188316060-09773afb-b164-446f-a37e-12a56eca54f5.png)

Additional Lantern in first person view

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.2 of Additional Lanterns.

Thank you for reporting the issue!
