### ISSUE TITLE
[Bug] Lanterns do not give off colored light in 1.12.2 even with Albedo

### ISSUE THREAD

**Issue by Shahelion** [SuperMartijn642/AdditionalLanterns#8]
**Version Info**
- Minecraft, 1.12.2
- Additional Lantern, 1.0.1a
- SuperMartijn642's Core lib, 1.0.19

**Description of the Bug**
Going by the screenshots, the lanterns should have colored light, but they do not.

**Comment by Zsashas** [comment]
Disregard this, turns out I still had Phosphor, which interferes with Albedo.

**Comment by SuperMartijn642** [comment]
The lanterns are not supposed to have colored lighting as Minecraft does not support that.
I assume you are talking about the screenshots on the CurseForge page for Additional Lanterns. Those screenshots were taken with OptiFine. Any colored lighting effects in those screenshots come from OptiFine. Additional Lanterns does nothing to add colored lighting.

**Comment by Shahelion** [comment]
Yeah, that makes sense.

**Comment by Shahelion** [comment]
Would it be possible to use Albedo to give the lanterns colored light?

**Comment by SuperMartijn642** [comment]
Additional Lanterns is available for 1.12 and 1.14 to 1.19. Albedo is only available 1.12 and 1.13, so I don't feel like it's worth the effort to add support for it for such an old version.
Additionally, there are just too many different colored lighting mods like Albedo. Just adding support for one seems rather odd when there are many similar mods, some of which even more popular.
